### ISSUE TITLE
Is there a way to set a timeout for SOAPConnection and WEBConnection requests?

### ISSUE THREAD

**Issue by pixelrebel** [predat/pyIsis#3]
I'm still struggling with hanging requests like get_workspaces() and get_server_info() on a couple Isises I have encountered.  Is there an option to specify the timeout length?

**Comment by predat** [comment]
Hello pixelrebel,

i've just push aa82dbd to replace suds with osa because it give better performance when retrieving workspaces. You need to install osa before using pyIsis. Can you try ?

Use it like this:

``` python
import pyIsis

credentials = {'username':'Administrator',
               'password': 'YOURPASSWORD',
               'hostname':'ISISIP'}

client = pyIsis.Client(**credentials)
workspaces = client.get_workspaces()

for workspace in workspaces:
    print workspace

```

PS: I've remove some functions like 'get_server_info'. I need to rewrite it...

**Comment by pixelrebel** [comment]
Thanks @predat!  This feels much faster!  

However, I still have an issue with my troubled isis (the one with 300+ workspaces).  When I call `get_workspaces()`, I receive the following error:

```
Traceback (most recent call last):
  File "pyisistest.py", line 8, in <module>
    workspaces = client.get_workspaces()
  File "/Library/Python/2.7/site-packages/pyIsis-0.1.0-py2.7.egg/pyIsis/connection.py", line 140, in get_workspaces
    return self._client.service.GetWorkspaces(self.token, '').workspaces.workspace
  File "/Library/Python/2.7/site-packages/osa/method.py", line 115, in __call__
    xml = xmlparser.parse_qualified(response)
  File "/Library/Python/2.7/site-packages/osa/xmlparser.py", line 52, in parse_qualified
    for event, element in etree.iterparse(f, events):
  File "<string>", line 84, in next
cElementTree.ParseError: not well-formed (invalid token): line 1, column 96279
```

Called `get_system_info()` on that one, however and it worked.

**Comment by predat** [comment]
osa (or cElementTree precisely) can't parse xml response from the server.
Perhaps you have a workspace name with a special character !?

Things you could try:

```
curl -s 'http://ISISIP/v2/ida' --data '&r=createsession&user=Administrator&pass=THEPASSWORD' | grep value
```

replace ISISIP with your server ip address and THEPASSWORD with your isis password.
This command return the authentication token.

```
curl 'http://ISISIP/' -H 'Cookie: AdminServerToken=THETOKEN; AgentLoginName=Administrator; avidagent=12345' \ 
  -H 'Connection: keep-alive' \
  --data '<?xml version="1.0" encoding="utf-8"?><SOAP-ENV:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><GetWorkspaces xmlns="urn:AdminServer"><inSessionToken>THETOKEN</inSessionToken><inStorageGroupIDs /></GetWorkspaces></SOAP-ENV:Body></SOAP-ENV:Envelope>'
```

replace THETOKEN into the previous command by the token that the server give you from the first curl.

It should return the SOAP xml response from the server containing all workspaces.

If you want you could send me this response.

**Comment by pixelrebel** [comment]
Thanks for this, it's great to see how all the data arrives under the hood.

I downloaded the xml result from the `GetWorkspaces` request.  Aside from a couple workspaces with dot `.` in the name, there were a few with spaces in the name.  Other than that, I found no special characters in the workspace names.  I also looked into the place where the error occurred, char 96279, and found nothing out of the ordinary.  

I took it one step further and ran the xml data thru the `parse_qualified()` method from `/Library/Python/2.7/site-packages/osa/xmlparser.py` and it successfully parsed the xml without errors.

Not sure what going on, but I would really appreciate it if you can take a look at the xml result of the workspace listing.  I just need to get permission before I can send it to you. 

Thanks for the help @predat!

**Comment by predat** [comment]
I'm really puzzled...
The xml file that you've send to me is completely valid. I can't find any error or special character into it.
Have you use my method to retrieve the response ? Have you copy/paste the result somewhere ? Or pipe the output directly into the file (with > ) ?
`parse_qualified()` need an object type file. You can try to modify osa/xmlparser.py (line 51) to save the file response somewhere before any treatment:

``` python
     with open('/tmp/response.xml', 'wb') as temp_response:
         temp_response.write(f.read())
         f.seek(0)
```

**Comment by pixelrebel** [comment]
Looks like the `urlopen()` file object doesn't support the `seek()` method.  `f.read()` destroys the object, so I was unable to make this test work.  

I originally did copy/paste method to retrieve the response, oops.  However, I just tried `> myisis.xml` that file failed to parse through `parse_qualified()`.  It failed on character 100328.  A different spot than pyIsis (character 96279).

So I checked it out and there is an anomaly (invisible character) in the `ioName`.  The workspace name is "A".

The weird thing is that there doesn't appear to be anything unusual about the name in the Management Console.  

Getting closer, but I'm still stumped...have to think about this one for a bit. 

I'm sending you the new xml so you can check it out.

Thanks!

**Comment by pixelrebel** [comment]
Actually, looking closer in the Web console.  Sure enough, that invisible character is truly in the workspace name!  Glad to get to the bottom of this.  Thanks for your help!

Now if I could figure out how to filter these nasty characters out of the `urlopen()` result... :)

On another note, do you plan to add back `get_system_info()` and the other old WEBConnection methods?

**Comment by pixelrebel** [comment]
This fixes it!  Haha!

In `osa/method.py: L106-119`:

```
        # real rpc
        try:
            response = urlopen(request)
            import StringIO, re
            scrubres = StringIO.StringIO(re.sub('[^\040-\176]', '', response.read()))
            del request
            # check http code returned
            if response.code == 200:
                if self.output is None:
                    return None
                # string to xml
                # use qualified parsing to get the anyType
                # type properly, unless it hits the performance heavily
                xml = xmlparser.parse_qualified(scrubres)
```

**Comment by pixelrebel** [comment]
@predat What needs to be done to add backwards compatibility for the WEBConnection methods?  `get_system_info()` doesn't return the same info as the old `get_server_info()` (GetSystemDirectorInfo).

Let me know if there's anything I can do to help.  I just need to be nudged into the right direction, and I can fill in the rest.

**Comment by predat** [comment]
look at this commit 7fbf9f7

**Comment by pixelrebel** [comment]
WooHoo, thanks @predat! And here's your PR: https://github.com/predat/pyIsis/pull/4
